disabled_rules:
  # 見やすさのため許可する制約
  - vertical_whitespace 
  - nesting
  - comma
  
  # 個々人の好み
  - statement_position
  - vertical_parameter_alignment
  - colon
  - closure_parameter_position
  - variable_name
  - trailing_comma

  # 許可しても問題バグの元にならない、かつ、許可した方が運用が楽
  - trailing_newline

  # 必要なシーンもあるので全面禁止にはしない
  # MEMO: テスト、レビューで安全を担保する必要はある
  - force_unwrapping
  - force_cast
  
included:
  - SearchList
  - SearchListTests
  
excluded:
  - SearchList/Resource/R.generated.swift
  - SearchListTests/Resource/R.generated.swift
  
line_length: 
  ignores_comments: true
  warning: 200
  error: 200

file_length:
  warning: 350
  error: 400
 
# わけない方が分かりやすい時もある
function_body_length: 100 

type_name:
  excluded:
     - Id
  max_length:
    warning: 50
    error: 60
